# Generated by Django 3.2.9 on 2021-12-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_cart_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
