# Generated by Django 3.2.9 on 2021-12-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20211209_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='key',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='success',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='txnid',
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
