# Generated by Django 3.2.9 on 2021-12-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_payment_txnid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
