# Generated by Django 3.2.9 on 2021-12-14 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_course',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.payment'),
        ),
    ]
