# Generated by Django 3.2.9 on 2021-12-21 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_my_course_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bank_ref_num',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bankcode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='error',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mihpayid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pg_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='productinfo',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='unmappedstatus',
        ),
        migrations.AddField(
            model_name='payment',
            name='bankname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='banktxnid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='checksumhash',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='gatewayname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentmode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='respcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='respmsg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='txnamount',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='txndate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txnid',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
