# Generated by Django 3.2.9 on 2021-12-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20211221_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isfree',
            field=models.BooleanField(default=False),
        ),
    ]
