# Generated by Django 3.2.9 on 2021-12-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_course_isfree'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
