# Generated by Django 3.2.9 on 2021-12-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_course_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='bought',
        ),
        migrations.RemoveField(
            model_name='course',
            name='certificate',
        ),
    ]
