# Generated by Django 3.2.9 on 2021-12-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_auto_20211223_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_course',
            name='certificate',
            field=models.BooleanField(default=False),
        ),
    ]
