# Generated by Django 3.2.9 on 2021-12-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_my_course_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ismycourse',
            field=models.BooleanField(default=False),
        ),
    ]
