# Generated by Django 3.2.9 on 2021-12-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_course_ismycourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ismycourse',
        ),
    ]
